"""
state.py

This file defines the "State" — the single shared object that gets passed
between every agent (node) in the LangGraph graph.

Think of State as a shared clipboard. Every agent reads from it, adds their
own piece of work to it, and passes the whole clipboard to the next agent.
This is the core idea of LangGraph: agents don't talk to each other directly,
they only read/write to this shared State.
"""

from typing import TypedDict


class PipelineState(TypedDict):
    """
    TypedDict = a dictionary with a fixed, known set of keys and types.
    LangGraph uses this to know what fields exist in the state and validate
    that nodes are returning the right shape of data.

    Fields:
        topic:          the subject the user wants content about (input)
        research_notes: bullet-point research generated by the Research Agent
        outline:        structured outline generated by the Planner Agent
        final_content:  the finished article generated by the Writer Agent
        current_step:   a human-readable label of which agent just ran —
                         this is ONLY used so the Streamlit UI can show a
                         live "trace" of progress. It has no effect on the
                         actual AI logic.
    """
    topic: str
    research_notes: str
    outline: str
    final_content: str
    current_step: str
